/*
 * Channel map — the CA-1 widget, also the EU-2 hardware swap.
 *
 * Bound to a PROJECT or LOCATION: "Deploy a LOGR" — pick a LOGR, pick or create
 * a station under the entity, name each active source. Bound to a STATION: its
 * own `config.channelMap`, where changing the LOGR moves the STATION -> DEVICE
 * relation instead of adding a second one. Map semantics:
 * logr-product-docs/cloud/CHANNEL_MAP.md; this widget:
 * logr-product-docs/cloud/CHANNEL_MAP_EDITOR.md.
 *
 * A LOGR's active sources are its own `subscriptions.<sourceKey>.enabled`
 * attributes; position labels and default names come from `config.peripherals`
 * on the Defaults asset, generated by the peripheral catalog.
 *
 * Loads after shared/resolver.js, glossary.js, ui.js and tb_io.js.
 */

window.TerrySenseChannelMapEditor = function (ctx, container) {

var resolver = window.TerrySenseResolver;
var tb = window.TerrySenseTbIo(ctx);
var io = tb.io;
var root = container.querySelector('.ts-root') || container;
var ui = window.TerrySenseUi(root);
var h = ui.h, esc = ui.esc, ICON = ui.ICON, info = ui.info;
var camel = resolver.camelKind;

// -- device topology / subscriptions (mirrors app/lib/catalog.py) ---------------

var EMPTY_MARKER = '(empty)';
var TOPOLOGY_TYPE_RE = /^topology\.p(\d+)\.type$/;
var SOURCE_KEY_RE = /^p(\d+)\.([a-z][A-Za-z0-9]*)(?:\.g(\d+))?(?:\.i(\d+))?$/;
// Converter-named device keys that are not measurements.
var DEVICE_WIDE_KEYS = ['uplinkCause', 'uplinkLatest'];

function topologyFrom(attrs) {
  var nodes = [];
  Object.keys(attrs).forEach(function (key) {
    var m = TOPOLOGY_TYPE_RE.exec(key);
    if (!m) { return; }
    var type = String(attrs[key] || '').trim();
    if (!type || type === EMPTY_MARKER) { return; }
    nodes.push({ position: Number(m[1]), type: type, version: attrs['topology.p' + m[1] + '.version'] });
  });
  return nodes.sort(function (a, b) { return a.position - b.position; });
}

function activeSourcesFrom(attrs) {
  return Object.keys(attrs).filter(function (key) {
    return key.indexOf('subscriptions.') === 0 && /\.enabled$/.test(key) && (attrs[key] === true || attrs[key] === 'true');
  }).map(function (key) {
    var sourceKey = key.slice('subscriptions.'.length, -'.enabled'.length);
    var m = SOURCE_KEY_RE.exec(sourceKey);
    if (!m) { return null; }
    return {
      sourceKey: sourceKey, position: Number(m[1]), kind: m[2],
      group: m[3] !== undefined ? Number(m[3]) : 0, index: m[4] !== undefined ? Number(m[4]) : 0
    };
  }).filter(Boolean).sort(function (a, b) { return a.position - b.position || a.sourceKey.localeCompare(b.sourceKey); });
}

function parseJson(raw) {
  if (!raw) { return null; }
  try { return typeof raw === 'string' ? JSON.parse(raw) : raw; } catch (e) { return null; }
}

function ago(ts) {
  if (!ts) { return 'never reported'; }
  var s = Math.max(0, (Date.now() - Number(ts)) / 1000);
  if (s < 90) { return 'just now'; }
  if (s < 5400) { return Math.round(s / 60) + ' min ago'; }
  if (s < 129600) { return Math.round(s / 3600) + ' h ago'; }
  return Math.round(s / 86400) + ' days ago';
}

// -- state ----------------------------------------------------------------------------

var state = {
  origin: null, swap: false, customer: null, readOnly: true,
  names: {}, kinds: {}, peripherals: {},
  devices: [], device: null, deviceStatus: null, topology: [], sources: [],
  stations: [], stationName: '',
  savedMap: null, map: {}, savedJson: '', showDiag: false
};

function kindLabel(kind) { return (resolver.kindSpec(kind, state.kinds) || {}).label || kind || 'Unknown kind'; }

function measureOf(src) {
  var node = state.topology.filter(function (n) { return n.position === src.position; })[0];
  var p = node && state.peripherals[node.type];
  return p && (p.measures || []).filter(function (m) {
    return camel(m.kind) === src.kind && m.group === src.group && m.index === src.index;
  })[0];
}

function sourceLabel(src) {
  var m = measureOf(src);
  var entry = m && state.names[m.defaultName];
  return entry && entry.label ? entry.label : kindLabel(src.kind);
}

function isDiagnostic(src) {
  var m = measureOf(src);
  return src.position === 0 || !!(m && (state.names[m.defaultName] || {}).diagnostic);
}

function namesForKind(kind) {
  return Object.keys(state.names).filter(function (n) { return camel(state.names[n].kind) === kind; })
    .sort(function (a, b) {
      return !!state.names[a].diagnostic - !!state.names[b].diagnostic || (state.names[a].label || a).localeCompare(state.names[b].label || b);
    });
}

// -- skeleton ---------------------------------------------------------------------------

root.innerHTML = '';
var cardEl = h('<div class="ts-card"><div class="ts-head"><div class="ts-head-icon">' + ICON.map + '</div><div class="ts-head-text">' +
  '<div class="ts-title"><span></span> ' + info('channelName') + '</div><div class="ts-subtitle"></div></div><span class="ts-chip level" hidden></span></div>' +
  '<div class="ts-body"><div class="ts-loading">Loading…</div></div>' +
  '<div class="ts-foot" hidden><span class="ts-summary"></span><span class="ts-spacer"></span><button type="button" class="ts-btn primary" disabled>Save</button></div></div>');
root.appendChild(cardEl);
var bodyEl = cardEl.querySelector('.ts-body');
var footEl = cardEl.querySelector('.ts-foot');
var saveBtn = footEl.querySelector('.ts-btn');
var summaryEl = footEl.querySelector('.ts-summary');

function fail(text) {
  bodyEl.innerHTML = '';
  bodyEl.appendChild(h('<div class="ts-empty"></div>')).textContent = text;
}

// -- load ---------------------------------------------------------------------------------

function listDevices() {
  var url = state.customer ? '/api/customer/' + state.customer.id + '/devices' : '/api/tenant/devices';
  return tb.get(url, { pageSize: '200', page: '0' }).then(function (p) { return (p && p.data) || []; });
}

function stationOfDevice(deviceId) {
  var query = {
    parameters: { rootId: deviceId, rootType: 'DEVICE', direction: 'TO', relationTypeGroup: 'COMMON', maxLevel: 1, fetchLastLevelOnly: false },
    filters: [{ relationType: 'Contains', entityTypes: ['ASSET'] }]
  };
  return tb.post('/api/relations/info', query).then(function (rels) {
    return rels && rels.length ? { id: rels[0].from.id, name: rels[0].fromName } : null;
  }).catch(function () { return null; });
}

function load() {
  return tb.boundDatasource().then(function (ds) {
    if (!ds || ds.entityType !== 'ASSET') { fail('No entity bound — bind a project, location or station in the widget\'s Data tab.'); return; }
    return tb.loadEntity(ds).then(function (origin) {
      state.origin = origin;
      state.swap = String(origin.kind || '').toLowerCase() === 'station';
      return Promise.all([resolver.buildChain(origin, io), tb.canWrite(origin), io.fetchAttrs(origin)]);
    }).then(function (got) {
      var chain = got[0];
      state.readOnly = !got[1];
      var customer = chain.filter(function (l) { return l.role === 'customer'; })[0];
      state.customer = customer ? { id: customer.id, name: customer.name } : null;
      var defaults = chain.filter(function (l) { return l.role === 'defaults'; })[0];
      var own = got[2];
      return Promise.all([
        defaults ? io.fetchAttrs(defaults) : Promise.resolve({}),
        listDevices(),
        state.swap ? Promise.resolve([]) : io.fetchChildren(state.origin)
      ]).then(function (more) {
        var d = more[0] || {};
        state.names = parseJson(d['config.channelNames']) || {};
        state.kinds = parseJson(d['config.kinds']) || {};
        state.peripherals = parseJson(d['config.peripherals']) || {};
        state.stations = (more[2] || []).filter(function (e) { return String(e.kind || '').toLowerCase() === 'station'; });
        return Promise.all(more[1].map(function (dev) {
          return stationOfDevice(dev.id.id).then(function (st) { return { id: dev.id.id, name: dev.name, type: dev.type, label: dev.label, station: st }; });
        }));
      }).then(function (devices) {
        state.devices = devices;
        state.savedMap = state.swap ? parseJson(own['config.channelMap']) : null;
        state.map = {};
        var channels = (state.savedMap && state.savedMap.channels) || {};
        Object.keys(channels).forEach(function (name) { state.map[channels[name]] = name; });
        state.savedJson = JSON.stringify(state.map);
        var savedDevice = state.savedMap && state.savedMap.sourceDeviceId;
        var first = savedDevice ? devices.filter(function (x) { return x.id === savedDevice; })[0] : null;
        if (!first && !state.swap) { first = devices.filter(function (x) { return !x.station; })[0] || null; }
        renderHead();
        return first ? selectDevice(first) : render();
      });
    });
  }).catch(function (err) { fail('Could not load: ' + (err && err.message ? err.message : err)); });
}

function selectDevice(device) {
  state.device = device;
  bodyEl.innerHTML = '<div class="ts-loading">Reading the LOGR…</div>';
  return Promise.all([
    tb.attrsMap({ entityType: 'DEVICE', id: device.id }, 'CLIENT_SCOPE'),
    tb.attrsMap({ entityType: 'DEVICE', id: device.id }, 'SERVER_SCOPE')
  ]).then(function (got) {
    var client = got[0], server = got[1];
    state.deviceStatus = { active: server.active === true || server.active === 'true', last: server.lastActivityTime };
    state.topology = topologyFrom(client);
    state.sources = activeSourcesFrom(client);
    if (state.sources.length || state.topology.length) { return; }
    return tb.get('/api/plugins/telemetry/DEVICE/' + device.id + '/keys/timeseries').then(function (keys) {
      // A LOGR that has not reported its topology yet is not a family device.
      var isLogr = (keys || []).some(function (k) { return SOURCE_KEY_RE.test(k); });
      state.sources = isLogr ? [] : (keys || []).filter(function (k) {
        return DEVICE_WIDE_KEYS.indexOf(k) < 0 && !/\.status$/.test(k);
      }).sort().map(function (k) {
        var entry = state.names[k];
        return { sourceKey: k, position: null, kind: entry ? camel(entry.kind) : null, offDictionary: !entry };
      });
    });
  }).then(function () {
    var keep = {};
    state.sources.forEach(function (s) { if (state.map[s.sourceKey]) { keep[s.sourceKey] = state.map[s.sourceKey]; } });
    state.map = keep;
    if (!state.swap) { prefill(); }
    render();
  });
}

// New deployment: each non-diagnostic source gets its catalog default name
// (a family device's key when it is a dictionary name), once per name.
function prefill() {
  var used = {};
  Object.keys(state.map).forEach(function (k) { used[state.map[k]] = true; });
  state.sources.forEach(function (s) {
    if (state.map[s.sourceKey] || isDiagnostic(s)) { return; }
    var m = measureOf(s);
    var name = m ? m.defaultName : (state.names[s.sourceKey] ? s.sourceKey : null);
    if (name && state.names[name] && !used[name]) { state.map[s.sourceKey] = name; used[name] = true; }
  });
}

// -- render --------------------------------------------------------------------------------

function renderHead() {
  cardEl.querySelector('.ts-title span').textContent = state.swap ? 'Channel map' : 'Deploy a LOGR';
  cardEl.querySelector('.ts-subtitle').textContent = state.swap
    ? 'Which sensor feeds which measurement of ' + state.origin.name
    : 'Connect a LOGR to a station in ' + state.origin.name;
  var chip = cardEl.querySelector('.ts-chip.level');
  chip.hidden = false;
  chip.textContent = state.origin.kind;
  cardEl.classList.toggle('ts-readonly', state.readOnly);
  footEl.hidden = false;
  saveBtn.hidden = state.readOnly;
}

function statusHtml() {
  if (!state.deviceStatus) { return ''; }
  var ok = state.deviceStatus.active;
  return '<span class="ts-status"><span class="ts-dot" style="background:' + (ok ? 'var(--ts-ok)' : 'var(--ts-danger)') + '"></span>' +
    esc(ago(state.deviceStatus.last)) + '</span>';
}

function render() {
  bodyEl.innerHTML = '';
  if (state.readOnly && !state.swap) {
    bodyEl.appendChild(h('<div class="ts-empty">Deploying a LOGR needs configuration rights on ' + esc(state.origin.name) + '.</div>'));
    footEl.hidden = true;
    return;
  }
  if (!Object.keys(state.names).length) {
    bodyEl.appendChild(h('<div class="ts-banner warn">' + ICON.info + '<span>No measurement names are available: the in-terra defaults are not shared with this customer, or the catalog was never synced. A tenant admin fixes either.</span></div>'));
  }

  // device
  var devRow = h('<div class="ts-kv"><div class="ts-kv-label">LOGR ' + info('device') + '</div><div class="ts-kv-value"></div></div>');
  var dv = devRow.querySelector('.ts-kv-value');
  if (state.readOnly) {
    dv.appendChild(h('<b></b>')).textContent = state.device ? state.device.name : 'none';
  } else {
    var sel = h('<select class="ts-select ts-grow"></select>');
    var none = h('<option value="">Pick a LOGR</option>');
    var free = h('<optgroup label="Not on a station"></optgroup>'), onStation = h('<optgroup label="Already on a station"></optgroup>');
    state.devices.forEach(function (d) {
      var o = document.createElement('option');
      o.value = d.id;
      var here = d.station && d.station.id === state.origin.id;
      o.textContent = (d.label || d.name) + (d.station && !here ? ' — ' + d.station.name : '');
      (d.station && !here ? onStation : free).appendChild(o);
    });
    sel.appendChild(none);
    if (free.children.length) { sel.appendChild(free); }
    if (onStation.children.length) { sel.appendChild(onStation); }
    sel.value = state.device ? state.device.id : '';
    sel.addEventListener('change', function () {
      var d = state.devices.filter(function (x) { return x.id === sel.value; })[0];
      if (d) { selectDevice(d); }
    });
    dv.appendChild(sel);
  }
  if (state.device) { dv.appendChild(h('<span>' + statusHtml() + '</span>')); }
  bodyEl.appendChild(devRow);

  // station (deploy mode)
  if (!state.swap) {
    var stRow = h('<div class="ts-kv"><div class="ts-kv-label">Station ' + info('station') + '</div><div class="ts-kv-value">' +
      '<input class="ts-input wide" placeholder="Pick a station or type a new name"><datalist></datalist><span class="ts-chip" hidden></span></div></div>');
    var listId = 'ts-st-' + Math.random().toString(36).slice(2);
    var input = stRow.querySelector('input'), dl = stRow.querySelector('datalist'), tag = stRow.querySelector('.ts-chip');
    dl.id = listId;
    input.setAttribute('list', listId);
    state.stations.forEach(function (s) { var o = document.createElement('option'); o.value = s.name; dl.appendChild(o); });
    input.value = state.stationName;
    var syncTag = function () {
      var existing = existingStation();
      tag.hidden = !state.stationName;
      tag.textContent = existing ? 'existing' : 'new';
      tag.className = 'ts-chip' + (existing ? '' : ' accent');
      updateFoot();
    };
    input.addEventListener('input', function () { state.stationName = input.value.trim(); syncTag(); });
    syncTag();
    bodyEl.appendChild(stRow);
  }

  if (state.swap && state.savedMap && state.device && state.savedMap.sourceDeviceId && state.savedMap.sourceDeviceId !== state.device.id) {
    bodyEl.appendChild(h('<div class="ts-banner">' + ICON.info + '<span>Hardware swap: the station keeps its measurement names and history. Map the new LOGR’s sensors to the same names.</span></div>'));
  }
  if (state.deviceStatus && !state.deviceStatus.active && state.device) {
    bodyEl.appendChild(h('<div class="ts-banner warn">' + ICON.info + '<span>This LOGR has not reported recently. Its sensor list may be out of date.</span></div>'));
  }

  // sources
  var sec = h('<div class="ts-section"><div class="ts-section-head">Sensors ' + info('position') + '</div></div>');
  if (!state.device) {
    sec.appendChild(h('<div class="ts-empty">Pick a LOGR above.</div>'));
  } else if (!state.sources.length) {
    sec.appendChild(h('<div class="ts-empty">No active sensor reported by this LOGR yet.</div>'));
  }
  var hidden = 0;
  var groups = state.topology.length
    ? state.topology.map(function (n) { return { position: n.position, node: n }; })
    : (state.sources.length ? [{ position: null, node: null }] : []);
  groups.forEach(function (g) {
    var srcs = state.sources.filter(function (s) { return s.position === g.position; }).filter(function (s) {
      var hide = isDiagnostic(s) && !state.map[s.sourceKey] && !state.showDiag;
      if (hide) { hidden++; }
      return !hide;
    });
    if (!srcs.length) { return; }
    var p = g.node && state.peripherals[g.node.type];
    var box = h('<div class="ts-pos"><div class="ts-pos-head"><span class="ts-pos-num"></span><span class="ts-pos-name"></span><span class="ts-mono"></span></div></div>');
    box.querySelector('.ts-pos-num').textContent = g.position === null ? '—' : g.position;
    box.querySelector('.ts-pos-name').textContent = g.node ? (g.position === 0 ? 'LOGR itself' : (p ? p.displayName : g.node.type)) : 'Device telemetry';
    box.querySelector('.ts-mono').textContent = g.node ? g.node.type + (g.node.version ? ' ' + g.node.version : '') : '';
    srcs.forEach(function (s) { box.appendChild(sourceRow(s)); });
    sec.appendChild(box);
  });
  if (hidden || state.showDiag) {
    var more = h('<button type="button" class="ts-more"></button>');
    more.textContent = state.showDiag ? 'Hide device diagnostics' : 'Show ' + hidden + ' device diagnostics';
    more.addEventListener('click', function () { state.showDiag = !state.showDiag; render(); });
    sec.appendChild(more);
  }
  bodyEl.appendChild(sec);
  updateFoot();
}

function sourceRow(s) {
  var row = h('<div class="ts-src"><div><div class="ts-row-label"></div><div class="ts-mono"></div></div>' +
    '<span class="ts-src-arrow">' + ICON.arrow + '</span><div></div></div>');
  row.querySelector('.ts-row-label').textContent = s.offDictionary ? s.sourceKey : sourceLabel(s);
  row.querySelector('.ts-mono').textContent = s.offDictionary ? 'not in the dictionary, kind unknown' : s.sourceKey;
  var target = row.lastChild;
  var name = state.map[s.sourceKey];
  var entry = name ? state.names[name] || {} : null;
  if (state.readOnly) {
    target.innerHTML = name ? '<div class="ts-row-label"></div><div class="ts-mono"></div>' : '<span class="ts-empty">not mapped</span>';
    if (name) { target.firstChild.textContent = entry.label || name; target.lastChild.textContent = name; }
    return row;
  }
  var btn = h('<button type="button" class="ts-name-btn' + (name ? '' : ' unmapped') + '"><span class="ts-grow"></span><span class="ts-chev">' + ICON.down + '</span></button>');
  var label = btn.querySelector('.ts-grow');
  if (name) {
    label.appendChild(h('<div></div>')).textContent = entry.label || name;
    label.appendChild(h('<div class="ts-mono"></div>')).textContent = name;
  } else {
    label.textContent = 'Not mapped';
  }
  btn.addEventListener('click', function () { openNamePicker(btn, s); });
  target.appendChild(btn);
  return row;
}

function openNamePicker(anchor, src) {
  var taken = {};
  Object.keys(state.map).forEach(function (k) { if (k !== src.sourceKey) { taken[state.map[k]] = true; } });
  var content = h('<div></div>');
  var pop;
  function pick(name) {
    if (name) { state.map[src.sourceKey] = name; } else { delete state.map[src.sourceKey]; }
    pop.close();
    render();
  }
  var none = ui.nameOption('', { label: 'Not mapped', description: 'The value is not stored on this station' }, '', state.map[src.sourceKey] ? '' : 'selected');
  none.querySelector('.ts-mono').remove();
  none.addEventListener('click', function () { pick(null); });
  content.appendChild(none);
  if (!src.kind) {
    content.appendChild(ui.namePicker({
      names: state.names, kinds: state.kinds,
      badge: function (n) { return taken[n] ? '<span class="ts-chip">used</span>' : ''; },
      onPick: function (n) { if (!taken[n]) { pick(n); } }
    }));
  } else {
    content.appendChild(h('<div class="ts-subhead"></div>')).textContent = kindLabel(src.kind) + ' names';
    var names = namesForKind(src.kind);
    names.forEach(function (n) {
      var e = state.names[n];
      var side = (taken[n] ? '<span class="ts-chip">used</span>' : '') + (e.diagnostic ? '<span class="ts-chip">diagnostic</span>' : '');
      var o = ui.nameOption(n, e, side, state.map[src.sourceKey] === n ? 'selected' : taken[n] ? 'taken' : '');
      if (!taken[n]) { o.addEventListener('click', function () { pick(n); }); }
      content.appendChild(o);
    });
    if (!names.length) {
      content.appendChild(h('<div class="ts-empty"></div>')).textContent = 'No name is declared for ' + kindLabel(src.kind) + '. A tenant admin adds one in the peripheral catalog or the channel dictionary.';
    }
  }
  pop = ui.popover(anchor, content);
}

// -- save ---------------------------------------------------------------------------------

function existingStation() {
  return state.stations.filter(function (s) { return s.name === state.stationName; })[0] || null;
}

function channelMap() {
  var channels = {};
  state.sources.forEach(function (s) { if (state.map[s.sourceKey]) { channels[state.map[s.sourceKey]] = s.sourceKey; } });
  return { sourceDeviceId: state.device ? state.device.id : null, channels: channels };
}

function updateFoot() {
  var n = Object.keys(channelMap().channels).length;
  summaryEl.textContent = n + (n === 1 ? ' measurement' : ' measurements') + ' mapped';
  var unchanged = state.swap && state.savedMap && state.device && state.savedMap.sourceDeviceId === state.device.id &&
    JSON.stringify(state.map) === state.savedJson;
  saveBtn.disabled = !state.device || !n || (!state.swap && !state.stationName) || unchanged;
}

function ensureStation() {
  if (state.swap) { return Promise.resolve(state.origin); }
  var existing = existingStation();
  if (existing) { return Promise.resolve(existing); }
  // A customer admin can only create assets owned by their own customer.
  var body = { name: state.stationName, type: 'Station' };
  if (state.customer) { body.customerId = { id: state.customer.id, entityType: 'CUSTOMER' }; }
  return tb.post('/api/asset', body).then(function (created) {
    var station = { entityType: 'ASSET', id: created.id.id, name: created.name, kind: 'Station' };
    return relate(state.origin.id, 'ASSET', station.id, 'ASSET').then(function () { return station; });
  });
}

function relate(fromId, fromType, toId, toType) {
  return tb.post('/api/relation', {
    from: { id: fromId, entityType: fromType }, to: { id: toId, entityType: toType }, type: 'Contains', typeGroup: 'COMMON'
  });
}

function stationDevice(stationId) {
  var query = {
    parameters: { rootId: stationId, rootType: 'ASSET', direction: 'FROM', relationTypeGroup: 'COMMON', maxLevel: 1, fetchLastLevelOnly: false },
    filters: [{ relationType: 'Contains', entityTypes: ['DEVICE'] }]
  };
  return tb.post('/api/relations', query).then(function (rels) { return rels && rels.length ? rels[0].to.id : null; });
}

function ensureDeviceRelation(station) {
  return stationDevice(station.id).then(function (current) {
    if (current === state.device.id) { return; }
    var work = current
      ? tb.del('/api/relation', { fromId: station.id, fromType: 'ASSET', toId: current, toType: 'DEVICE', relationType: 'Contains', relationTypeGroup: 'COMMON' })
      : Promise.resolve();
    return work.then(function () { return relate(station.id, 'ASSET', state.device.id, 'DEVICE'); });
  });
}

saveBtn.addEventListener('click', function () {
  var creating = !state.swap && !existingStation();
  var moving = state.swap && state.savedMap && state.savedMap.sourceDeviceId && state.savedMap.sourceDeviceId !== state.device.id;
  var device = esc(state.device.label || state.device.name);
  var text = state.swap
    ? (moving ? 'Move <b>' + esc(state.origin.name) + '</b> to <b>' + device + '</b>? The history stays on the station.' : 'Save the channel map of <b>' + esc(state.origin.name) + '</b>?')
    : (creating ? 'Create station <b>' + esc(state.stationName) + '</b> in ' + esc(state.origin.name) + ' and connect <b>' + device + '</b>?'
      : 'Connect <b>' + device + '</b> to <b>' + esc(state.stationName) + '</b>?');
  ui.confirm(text, 'Save').then(function (ok) {
    if (!ok) { return; }
    saveBtn.disabled = true;
    var station;
    return ensureStation().then(function (s) {
      station = s;
      return ensureDeviceRelation(station);
    }).then(function () {
      return tb.saveAttrs(station, { 'config.channelMap': channelMap() });
    }).then(function () {
      return tb.resolveStations([station]);
    }).then(function () {
      ui.toast(state.swap ? 'Channel map saved' : creating ? 'Station created, LOGR connected' : 'LOGR connected');
      state.stationName = '';
      return load();
    }).catch(function (err) {
      saveBtn.disabled = false;
      ui.toast('Save failed: ' + (err && (err.message || (err.error && err.error.message)) || err), 'error');
    });
  });
});

load();

};
